midas = ['BROOKVALE',
'CAMPSIE',
'HORNSBY',
'WEST RYDE',
'COOKS HILL',
'CHATSWOOD',
'BANKSTOWN',
'BLACKTOWN',
'CAMPBELLTOWN',
'CONCORD',
'FAIRFIELD',
'HABERFIELD',
'LIVERPOOL',
'PEAKHURST',
'PENRITH',
'ROCKDALE',
'TAREN POINT',
'WOOLLAHRA',
'BASS HILL',
'HEATHCOTE',
'GOSFORD',
'ROUSE HILL',
'ARMIDALE',
'CABOOLTURE',
'ENOGGERA',
'WOOLLOONGABBA',
'MANSFIELD',
'ASHGROVE',
'BEENLEIGH',
'CAPALABA',
'INDOOROOPILLY',
'IPSWICH',
'TINGALPA',
'SPRINGWOOD',
'ALBION',
'KIPPA-RING',
'STRATHPINE',
'BURLEIGH HEADS',
'BIGGERA WATERS',
'SOUTHPORT',
'MAROOCHYDORE',
'GEEBUNG',
'TWEED HEADS',
'CAIRNS',
'BALWYN',
'BLACKBURN',
'BRIGHTON',
'ESSENDON',
'GREENSBOROUGH',
'OAKLEIGH',
'SOUTH MELBOURNE',
'SUNSHINE',
'YARRAVILLE',
'WERRIBEE PLAZA',
'KEW',
'HIGHPOINT',
'FRANKSTON',
'HOPPERS CROSSING',
'CAROLINE SPRINGS',
'BALLARAT',
'SALISBURY',
'CLOVELLY PARK',
'MAGILL',
'MORPHETT VALE',
'PORT ADELAIDE',
'PROSPECT',
'DARLINGTON',
'PARA HILLS',
'HARBOUR TOWN SA',
'PORT KENNEDY',
'FREMANTLE',
'MIDLAND',
'CANNING VALE',
'HOBART',
'LAUNCESTON',
'BELMONT',
'FERNTREE GULLY',
'MOSMAN',
'Melton',
'BRUNSWICK',
'COLLINGWOOD',
'EPPING',
'HEIDELBERG',
'ELTHAM',
'BALWYN',
'RINGWOOD',
'SPRINGVALE',
'MOORABBIN',
'SEAFORD VIC',
'SOUTH MELBOURNE',
'GEELONG',
'COLAC',
'SHEPPARTON',
'WODONGA',
'MORNINGTON',
'MT OMMANEY',
'WOOLLOONGABBA',
'CLEVELAND',
'CABOOLTURE',
'KAWANA',
'ADELAIDE',
'ROSEWATER',
'KESWICK',
'MELROSE PARK',
'GLYNDE',
'RIDGEHAVEN',
'SALISBURY',
'MORPHETT VALE',
'SEAFORD SA',
'MIDLAND',
'HOBART',
'GLENORCHY',
]

mh_au = ['Miranda',
'Roselands',
'Warringah Mall',
'Bankstown Square',
'Burwood',
'Hornsby',
'Hurstville',
'East Gardens',
'Southgate',
'Top Ryde',
'Chatswood',
'Broadway Mall',
'George St Sydney CBD',
'Liverpool',
'Castle Towers',
'Winston Hills',
'Merrylands',
'Parramatta',
'Erina Fair',
'Port Macquarie',
'Jesmond',
'Tuggerah',
'Charlestown',
'Coffs Harbour',
'Dubbo',
'Tamworth',
'Maitland',
'Lismore',
'Raymond Terrace',
'Glendale',
'Kotara',
'Forster',
'Lake Macquarie Fair',
'Lake Haven',
'Singleton',
'Woden',
'Belconnen',
'Shell Harbour Square',
'MacArthur Square',
'Crown Central Wollongong',
'Tuggeranong',
'Dapto Mall',
'Narellan',
'Canberra Centre',
'Highlands Market Place',
'Goulburn',
'Penrith',
'Blacktown',
'Campbelltown',
'Mt Druitt',
'Wetherill Park',
'Rouse Hill',
'Bathurst',
'Grand Central',
'Loganholme',
'Clifford Gardens',
'Mt Ommaney',
'Indooroopilly',
'Capalaba Park',
'Pacific Fair',
'Browns Plains',
'Helensvale',
'Ipswich Riverlink',
'Garden City',
'Carindale',
'Robina',
'Queens Plaza',
'Harbourtown',
'Coomera',
'Rockhampton',
'Cairns',
'Chermside',
'Strathpine',
'Mackay Canelands',
'The Willows',
'Maroochydore',
'Kawana Waters',
'Townsville Stockland',
'Cairns Central',
'North Lakes',
'Morayfield',
'Castletown',
'Peninsula Fair',
'Hinkler',
'Hervey Bay',
'DFO Brisbane',
'Rosny Park',
'Hobart CBD',
'Launceston',
'Northgate Hobart',
'Greensborough',
'Broadmeadows',
'Epping Plaza',
'Plenty Valley',
'Northland',
'Doncaster',
'Craigieburn',
'Airport West',
'DFO Essendon',
'Eastlands',
'Chirnside Park',
'Forest Hill',
'DFO Moorabbin',
'Mildura',
'Fountain Gate',
'The Glen',
'Dandenong',
'Knox City',
'Parkmore',
'Bayside North',
'Karingal',
'Southland',
'Wendouree',
'Cranbourne Park',
'Casey Victoria',
'Chadstone',
'Warrnambool',
'Wagga Wagga',
'Albury Wodonga',
'Highpoint',
'Werribee',
'Geelong',
'Watergardens',
'Bendigo',
'Sunshine Marketplace',
'Melbourne CBD',
'Shepparton',
'Woodgrove - Melton',
'Waurn Ponds',
'Bourke Street',
'Karrinyup',
'Warwick Grove',
'Mirrabooka Square',
'Innaloo',
'Midland Gate',
'Joondalup',
'Perth CBD',
'Geraldton',
'Ocean Keys',
'Belmont Forum',
'Galleria',
'Carousel',
'Booragoon',
'Whitford City',
'Armadale (WA)',
'Gateways',
'DFO Perth',
'Elizabeth',
'Tea Tree Plaza',
'Arndale',
'Colonnades',
'West Lakes',
'Marion',
'Rundle Mall',
'Mt Gambier',
'Rockingham',
'Bunbury',
'Albany Plaza 528',
'Eaton Fair',
'Baldivis',
'Darwin Casuarina',
'Halls Head',
'Palmerston',
'Mandurah',
]

mh_ca = ['Mayfair',
'Woodgrove',
'Cherry Lane',
'Hillside',
'Guildford Town Centre',
'Aberdeen',
'Tsawwassen',
'Village Green',
'Orchard Park',
'Lougheed',
'Seven Oaks',
'Metrotown Centre',
'Willowbrook Shopping Centre',
'Cottonwood',
'Richmond Centre',
'Pine Centre',
'Park Royal',
'Brentwood',
'McAthur Glen Outlet',
'Fairview Park',
'Pen Centre',
'Masonville',
'White Oaks',
'Cambridge',
'Devonshire',
'Stone Road',
'Niagara',
'Oakville Place',
'Limeridge',
'Lynden Park',
'Halifax',
'Conestoga Mall',
'McAllister Place',
'Regent Mall',
'Charlottetown',
'Maple View',
'Burlington Centre',
'Pickering',
'Oshawa',
'Scarborough Town Centre',
'Markville',
'St Laurent',
'Hillcrest',
'Bayshore',
'Place D`Orleans',
'Yorkdale',
'Cataraqui',
'Carlingwood',
'Cadillac Fairview Mall',
'Rideau Centre',
'Quinte Mall',
'Kildonan',
'Polo Park',
'St Vital',
'Brandon',
'Winnipeg Outlet',
'Kingsway Garden Mall',
'West Edmonton Mall',
'Prairie Mall',
'Edmonton City Centre',
'Peter Pond',
'Sherwood Park',
'Londonderry Mall',
'St Albert',
'Edmonton Outlet',
'Sunridge Mall',
'Marlborough',
'South Centre',
'Crossiron Mills',
'Bower Place',
'Chinook',
'Midtown Plaza',
'Market Mall',
'Medicine Hat Mall',
'Park Place',
'Bramalea',
'Upper Canada Mall',
'Georgian Mall',
'Dufferin',
'Yonge Eglinton',
'Inter City',
'Erin Mills',
'Sherway',
'Square One',
'Vaughan Mills',
'North Bay',
'New Sudbury',
]